apiVersion: v1
kind: Service
metadata:
  name: uvicorn-debug
  labels:
    app: uvicorn-debug
spec:
  type: ClusterIP
  selector:
    app: uvicorn-debug
  ports:
    - name: http
      port: 80
      targetPort: 8000
